development:
  adapter: postgresql
  database: racer_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: racer_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: racer_production
  pool: 5
  timeout: 5000
